compile SCGCF504.PRG
compile DELOSI.PRG
compile EXPOCRR.PRG
compile MN_ANUAL.PRG
compile NF_X_IT.PRG
compile PREPARA.PRG
compile TESTE2.PRG
compile INVT_TMP.PRG
compile SOMA_DUP.PRG
compile TESTELPT.PRG
compile CRIA_IDX.PRG
compile TESTE6.PRG
compile ROT_IMPR.PRG
compile TESTE5.PRG
compile MN_NOVO.PRG
compile SCGC201A.PRG
compile CTR_ITEM.PRG
compile CHC_SLD.PRG
compile PROCURA.PRG
compile T1.PRG
compile TESTE4.PRG
compile SCGC216.PRG
compile RECIBO.PRG
compile SCGCLIMP.PRG
compile TMPCOMIS.PRG
compile PAT_TEMP.PRG
compile TMP2.PRG
compile CL_ATIVO.PRG
compile PIS_1010.PRG
compile AJSTDP10.PRG
compile TMP50.PRG
compile TMP8.PRG
compile TESTE50.PRG
compile PIS_0709.PRG
compile CPFCNPJ.PRG
compile RELFIM.PRG
compile SCGCECF.PRG
compile SCGCF505.PRG
compile CHQ_DUP2.PRG
compile SCGC001.PRG
compile F.PRG
compile PROJCX.PRG
compile SYSTEM.PRG
compile CHQ_DUP.PRG
compile SCGCF201.PRG
compile OLIVEIRA.PRG
compile SVD0500E.PRG
compile CLNT_TMP.PRG
compile SOMA_NF.PRG
compile RELINIC.PRG
compile SVD0500A.PRG
compile TMP3.PRG
compile PROJSVD.PRG
compile RECUPPED.PRG
compile SCGC202.PRG
compile RECUPRT.PRG
compile OBJ_ATLZ.PRG
compile ATRBIBGE.PRG
compile AJST_131.PRG
compile SVD2.PRG
compile REC_ITMA.PRG
compile ROTESTOQ.PRG
compile SCGC2.PRG
compile SVD0500B.PRG
compile PIS_0810.PRG
compile PAT3.PRG
compile REC_CLIE.PRG
compile TMP1.PRG
compile RECUPDUP.PRG
compile TESTE8.PRG
compile RECUPCLI.PRG
compile TESTE10.PRG
compile TMP_867.PRG
compile T.PRG
compile ESTQ0100.PRG
compile T2.PRG
compile DF.PRG
compile TMP10.PRG
compile F2.PRG
compile REORD.PRG
compile CTR_ESTQ.PRG
compile SCGC201.PRG
compile RELCLI.PRG
compile RECUPNF.PRG
compile VER_ARQ.PRG
compile RELLINHA.PRG
compile REC_ORTM.PRG
compile TESTE60.PRG
compile TMP_INVT.PRG
compile INVT.PRG
compile TESTE3.PRG
compile MOV13_14.PRG
compile RENUM.PRG
compile SVD0500C.PRG
compile COM1WR.PRG
compile TMP_1.PRG
compile REC_ITEM.PRG
compile SCGCCOMP.PRG
compile TMP_CLIE.PRG
compile AJST_TDS.PRG
compile TMP.PRG
compile REC_ORCA.PRG
compile SCGC210.PRG
compile SVD0500D.PRGf
compile SCT00000.PRG
compile SOMA_NFE.PRG
compile CHQ_DUP3.PRG
compile SCGC204.PRG
compile RECUPERA.PRG
compile SCGC800E.PRG
compile REL000.PRG
compile H010.PRG
compile CPR_IT.PRG
compile REC_CMS.PRG
compile TRESTE.PRG
compile RECUPITE.PRG
compile SCGCF211.PRG
compile AJST_IVT.PRG
compile SCGCF506.PRG
compile SEPARA.PRG
compile GERA_BLT.PRG
compile TMPNFSDA.PRG
compile TMPNFENT.PRG
compile TMP5.PRG
compile DUPLICI.PRG
compile TMP15.PRG
compile AMB.PRG
compile RESTAURA.PRG
