create table DOCFISCAIS (
DFIS_ID              INTEGER                        not null,
DFIS_NAT_OPERACAO    VARCHAR(40),
DFIS_IND_OPERACAO    VARCHAR(1)                     not null,
DFIS_TP_MOVIMENTO    VARCHAR(7)                     not null,
DFIS_IND_EMITENTE    VARCHAR(1)                     not null,
DFIS_MOD_DOCUMENTO   VARCHAR(2),
DFIS_CDG_SITUACAO    VARCHAR(9)                     not null,
DFIS_NRO_DOCUMENTO   VARCHAR(10),
DFIS_SERIE           VARCHAR(3),
DFIS_MOD_NOTA        VARCHAR(2),
DFIS_CHV_NFE         VARCHAR(44),
DFIS_DGT_CHV_NFE     CHAR(1),
DFIS_DT_DOC          DATE,
DFIS_DT_ENT_OU_SAIDA DATE,
DFIS_DT_CANC         DATE,
DFIS_VLR_DOCUMENTO   NUMERIC(18,4)                  not null,
DFIS_TP_PGTO_CODIGO  VARCHAR(1)                     not null,
DFIS_TP_PGTO_DESCRICAO VARCHAR(15),
DFIS_VLR_DESCONTO    NUMERIC(18,4)                  not null,
DFIS_VLR_ABATE_NT    NUMERIC(18,4)                  not null,
DFIS_VL_MERCADORIAS  NUMERIC(18,4)                  not null,
DFIS_VLR_FRETE       NUMERIC(18,4)                  not null,
DFIS_VLR_SEGURO      NUMERIC(18,4)                  not null,
DFIS_VLR_DESPESAS    NUMERIC(18,4)                  not null,
DFIS_OUT_DESP_ACES   NUMERIC(18,4)                  not null,
DFIS_BC_ICMS         NUMERIC(18,4)                  not null,
DFIS_VLR_ICMS        NUMERIC(18,4)                  not null,
DFIS_BC_ICMS_RTD     NUMERIC(18,4)                  not null,
DFIS_VLR_ICMS_RTD    NUMERIC(18,4)                  not null,
DFIS_BC_IPI          NUMERIC(18,4)                  not null,
DFIS_VL_IPI          NUMERIC(18,4)                  not null,
DFIS_VLR_PIS         NUMERIC(18,4)                  not null,
DFIS_VLR_COFINS      NUMERIC(18,4)                  not null,
DFIS_VLR_PIS_RTD     NUMERIC(18,4)                  not null,
DFIS_VLR_COFINS_RTD  NUMERIC(18,4)                  not null,
DFIS_INF_COMPLEMENTARES LONG VARBINARY,
DFIS_NRO_PROC_CONCESSORIO VARCHAR(20),
DFIS_ORIGEM_PROC_CONCESSORIO VARCHAR(1),
DFIS_TP_DOC_IMPORTACAO VARCHAR(1),
DFIS_NRO_DOC_IMPORTACAO VARCHAR(10),
DFIS_VLR_PIS_IMPORTACAO NUMERIC(18,4)                  not null,
DFIS_VLR_COFINS_IMPORTACAO NUMERIC(18,4)                  not null,
DFIS_VLR_SERVICO_NT  NUMERIC(18,4)                  not null,
DFIS_VLR_BC_ISSQN    NUMERIC(18,4)                  not null,
DFIS_VLR_ISSQN       NUMERIC(18,4)                  not null,
DFIS_VLR_BC_IRRF     NUMERIC(18,4)                  not null,
DFIS_VLR_IRRF        NUMERIC(18,4)                  not null,
DFIS_VLR_BC_PREVIDENCIA NUMERIC(18,4)                  not null,
DFIS_VLR_PREVIDENCIA NUMERIC(18,4)                  not null,
DFIS_AUT_SEFAZ_COMBUSTIVEL VARCHAR(10)                    not null,
DFIS_NRO_PASSE_FISCAL VARCHAR(10)                    not null,
DFIS_TEMPERATURA     NUMERIC(6,1)                   not null,
DFIS_CPFCNPJ         VARCHAR(20),
DFIS_UF              VARCHAR(2),
DFIS_IE              VARCHAR(20),
DFIS_NOME            VARCHAR(250),
DFIS_RAZAO_SOCIAL    VARCHAR(100),
DFIS_TP_LOGRADOURO   VARCHAR(20),
DFIS_LOGRADOURO      VARCHAR(60),
DFIS_NRO_LOGRADOURO  VARCHAR(10),
DFIS_COMPL_LOGRADOURO VARCHAR(25),
DFIS_CEP             VARCHAR(10),
DFIS_ZONA            VARCHAR(15),
DFIS_MUNI_IBGE       VARCHAR(10),
DFIS_MUNI_NOME       VARCHAR(60),
DFIS_BAIRRO          VARCHAR(60),
DFIS_PAIS            VARCHAR(60),
DFIS_FONE            VARCHAR(10),
DFIS_IE_SUB_TRIB     VARCHAR(20),
DFIS_SUFRAMA         VARCHAR(9),
DFIS_REF_NRO_DOCUMENTO VARCHAR(10),
DFIS_REF_SERIE       VARCHAR(3),
DFIS_REF_DT_DOC      DATE,
DFIS_REF_IND_OPERACAO VARCHAR(1)                     not null,
DFIS_REF_TP_MOVIMENTO VARCHAR(7)                     not null,
DFIS_REF_IND_EMITENTE VARCHAR(1)                     not null,
DFIS_REF_MOD_DOCUMENTO VARCHAR(2),
DFIS_NRO_SERIAL_ECF  VARCHAR(25),
DFIS_NRO_CAIXA_ECF   VARCHAR(5),
DFIS_NRO_CUPOM__COO_ECF VARCHAR(10)
);

create table DOCFISITENS (
DFIT_PK              INTEGER                        not null,
DFIT_NRO_ITEM        VARCHAR(5)                     not null,
DFIT_PROD_CODIGO     VARCHAR(10),
DFIT_PROD_DESCRICAO  VARCHAR(60),
DFIT_PROD_DESCR_COMPL VARCHAR(60),
DFIT_UN_TAB          VARCHAR(3)                     not null,
DFIT_UN_VENDA        VARCHAR(3)                     not null,
DFIT_UN_PADRAO       VARCHAR(3)                     not null,
DFIT_UNIDADE         VARCHAR(3)                     not null,
DFIT_CONV_UN_TAB_VDA NUMERIC(18,6)                  not null,
DFIT_CONV_UN_VDA_PADRAO NUMERIC(18,6)                  not null,
DFIT_PRECO_TAB       NUMERIC(18,4)                  not null,
DFIT_PRECO_UN_VDA    NUMERIC(18,4)                  not null,
DFIT_PRECO_MAX_TABELADO NUMERIC(18,4)                  not null,
DFIT_PRECO_MIN_TABELADO NUMERIC(18,4)                  not null,
DFIT_PRECO_UN_PADRAO NUMERIC(18,4)                  not null,
DFIT_PRECO_UNITARIO  NUMERIC(18,4)                  not null,
DFIT_QTDE_UN_VENDA   NUMERIC(18,6)                  not null,
DFIT_QTDE_UN_PADRAO  NUMERIC(18,6)                  not null,
DFIT_QTDE            NUMERIC(18,6)                  not null,
DFIT_VLR_DESCONTO    NUMERIC(18,4)                  not null,
DFIT_VLR_DESP_FINANCEIRA NUMERIC(18,4)                  not null,
DFIT_VLR_OUTRAS_DESP_ACES NUMERIC(18,4)                  not null,
IDCFI_CUSTO_FRETE    NUMERIC(18,4)                  not null,
IDCFI_CUSTO_SEGURO   NUMERIC(18,4)                  not null,
DFIT_VLR_FINAL       NUMERIC(18,4)                  not null,
DFIT_MENSAGEM        VARCHAR(250),
DFIT_IND_MOVIMENTO_ESTQ VARCHAR(3),
DFIT_LOTE_QTDE_ITENS NUMERIC(18,6)                  not null,
DFIT_LOTE_NRO        VARCHAR(10)                    not null,
DFIT_LOTE_FABRICACAO DATE                           not null,
DFIT_LOTE_VALIDADE   DATE                           not null
);

create table DOCFISTITULOS (
DFTT_ID              INTEGER                        not null,
DFTT_TP_CREDITO      VARCHAR(2),
DFTT_DESCR_TITULO_CREDITO VARCHAR(50),
DCFS_                VARCHAR(10),
DFTT_QTDE_PARC       VARCHAR(5)                     not null,
DFTT_STRING_DE_VENC  VARCHAR(255),
DFTT_VLR_PRIMEIRA_PARC NUMERIC(18,4)                  not null
);

create table DOCFISTRANSPORTE (
DFTR_ID              INTEGER                        not null,
DFTR_TEMPERATURA     NUMERIC(6,1)                   not null,
DFTR_TP_FRETE        VARCHAR(1)                     not null,
DFTR_TP_CARGA        VARCHAR(1),
DFTR_PLACA_UF        VARCHAR(2),
DFTR_PLACA_VEICULO   VARCHAR(7),
DFTR_CPFCNPJ         VARCHAR(20),
DFTR_NOME            VARCHAR(60),
DFTR_UF              VARCHAR(2),
DFTR_IE              VARCHAR(20),
DFTR_TP_LOGRADOURO   VARCHAR(20),
DFTR_LOGRADOURO      VARCHAR(60),
DFTR_NRO             VARCHAR(10),
DFTR_COMPLEMENTO     VARCHAR(25),
DCFS_TRANSP_CEP_     VARCHAR(10),
DCFS_PART_MUNI_IBGE2 VARCHAR(10),
DFTR_MUNI_NOME       VARCHAR(60),
DFTR_BAIRRO          VARCHAR(60),
DFTR_PAIS            VARCHAR(60),
DFTR_FONE            VARCHAR(10),
DFTR_LOCAL_COLETA_CPFCNPJ VARCHAR(20),
DFTR_LOCAL_COLETA_IE VARCHAR(20),
DFTR_LOCAL_COLETA_NOME VARCHAR(250),
DFTR_LOCAL_COLETA_MUNI_IBGE VARCHAR(10),
DFTR_LOCAL_COLETA_ENDERECO VARCHAR(100),
DFTR_LOCAL_ENTREGA_CPFCNPJ VARCHAR(20),
DFTR_LOCAL_ENTREGA_IE VARCHAR(20),
DFTR_LOCAL_ENTREGA_NOME VARCHAR(250),
DFTR_LOCAL_ENTREGA_MUNI_IBGE VARCHAR(10),
DFTR_LOCAL_ENTREGA_END VARCHAR(100),
DFTR_QTDE_VOLUMES    NUMERIC(18,6)                  not null,
DFTR_ESPECIE         VARCHAR(5)                     not null,
DFTR_MARCA           VARCHAR(5)                     not null,
DFTR_PESO_BRUTO      NUMERIC(18,6)                  not null,
DFTR_PESO_LIQUIDO    NUMERIC(18,6)                  not null,
DFTR_HORA_SAIDA      DATE                           not null
);

create table DOCFISTRBITENS (
DFTI_PK              INTEGER                        not null,
DFTI_VLR_A_TRIBUTAR  NUMERIC(18,4)                  not null,
DFTI_CUSTO_NA_OPERACAO NUMERIC(18,4)                  not null,
DFTI_CUSTO_MEDIO_ANT NUMERIC(18,4)                  not null,
DFTI_SALDO_ANTERIOR  NUMERIC(18,6)                  not null,
DFTI_CUSTO_MEDIO_ATUAL NUMERIC(18,4)                  not null,
DFTI_SALDO_ATUAL     NUMERIC(18,6)                  not null,
DFTI_CUSTO_CONTABIL  NUMERIC(18,4)                  not null,
DFTI_CFO             VARCHAR(5)                     not null,
DFTI_CST_ICMS        VARCHAR(3)                     not null,
DFTI_CST_IPI         VARCHAR(2)                     not null,
DFTI_CST_ISS         VARCHAR(2)                     not null,
DFTI_CST_PIS         VARCHAR(2)                     not null,
DFTI_CST_COFINS      VARCHAR(2)                     not null,
DFTI_CST_IR          VARCHAR(2)                     not null,
DFTI_BC_BRUTA_ICMS   NUMERIC(18,4)                  not null,
DFTI_IND_REDUCAO     NUMERIC(6,3)                   not null,
DFTI_BC_ICMS         NUMERIC(18,4)                  not null,
DFTI_ALIQ_ICMS_ORIGEM NUMERIC(6,3)                   not null,
DFTI_ALIQ_ICMS_DESTINO NUMERIC(6,3)                   not null,
DFTI_DIF_ALIQUOTA    NUMERIC(18,4)                  not null,
DFTI_ALIQ_ICMS       NUMERIC(6,3)                   not null,
DFTI_VLR_ICMS        NUMERIC(18,4)                  not null,
DFTI_REG_FISCAL_TRIB_ORIGEM VARCHAR(23)                    not null,
DFTI_REG_FISCAL_TRIB_DESTINO VARCHAR(23)                    not null,
DFTI_BASE_ISENTA_ICMS NUMERIC(18,4)                  not null,
DFTI_BASE_OUTR_ICMS  NUMERIC(18,4)                  not null,
DFTI_BC_BRUTA_RTD    NUMERIC(18,4)                  not null,
DFTI_IVA             NUMERIC(6,3)                   not null,
DFTI_BC_SUBST        NUMERIC(18,4)                  not null,
DFTI_ALIQ_ICMS_SUBST NUMERIC(6,3)                   not null,
DFTI_ICMS_SUBST_RTD_SAIDA NUMERIC(18,4)                  not null,
DFTI_BC_BRUTA_RTD_ENTRADA NUMERIC(18,4)                  not null,
DFTI_BC_RTD_ENTRADA  NUMERIC(18,4)                  not null,
DFTI_ICMS_RTD_ENTRADA NUMERIC(18,4)                  not null,
DFTI_IND_APURACAO_IPI VARCHAR(9)                     not null,
DFTI_CON_ENQ_IPI     VARCHAR(3)                     not null,
DFTI_BC_IPI          NUMERIC(18,4)                  not null,
DFTI_ALIQ_IPI        NUMERIC(6,3)                   not null,
DFTI_VLR_IPI         NUMERIC(18,4)                  not null,
DFTI_BC_ISS          NUMERIC(18,4)                  not null,
DFTI_ALIQ_ISS        NUMERIC(6,3)                   not null,
DFTI_VLR_ISS         NUMERIC(18,4)                  not null,
DFTI_BC_ISS_RTD      NUMERIC(18,4)                  not null,
DFTI_ALIQ_ISS_RTD    NUMERIC(6,3)                   not null,
DFTI_ISS_RTD         NUMERIC(18,4)                  not null,
DFTI_BC_PIS          NUMERIC(18,4)                  not null,
DFTI_ALIQ_PIS        NUMERIC(6,3)                   not null,
DFTI_QTDE_BASE_PIS   NUMERIC(18,6)                  not null,
DFTI_VLR_PIS         NUMERIC(18,4)                  not null,
DFTI_PIS_RTD         NUMERIC(18,4)                  not null,
DFTI_BC_COFINS       NUMERIC(18,4)                  not null,
DFTI_ALIQ_COFINS     NUMERIC(6,3)                   not null,
DFTI_QTDE_BASE_COFINS NUMERIC(18,6)                  not null,
DFTI_VLR_COFINS      NUMERIC(18,4)                  not null,
DFTI_COFINS_RTD      NUMERIC(18,4)                  not null,
DFTI_BC_IR           NUMERIC(18,4)                  not null,
DFTI_ALIQ_IR         NUMERIC(6,3)                   not null,
DFTI_VLR_IR          NUMERIC(18,4)                  not null,
DFTI_IR_RTD          NUMERIC(18,4)                  not null,
DFTI_BC_CSLL         NUMERIC(18,4)                  not null,
DFTI_ALIQ_CSLL       NUMERIC(6,3)                   not null,
DFTI_VLR_CSLL        NUMERIC(18,4)                  not null,
DFTI_ADIANTAMENTO_CSLL NUMERIC(18,4)                  not null,
DFTI_LANC_AUTOMATICO VARCHAR(3)                     not null
);

